#!/bin/bash
DIA=1
BASE_AMOSTRAS=300
function help() {
        echo Como utilizar este comando:
        echo $0 \(dia\|hora\) \(quantidade de tempo\)
}
function FNMON() {
        DURACAO=$(expr $2 \* 3600)
        INTERVALO=$1
        AMOSTRAS=$(expr $DURACAO \/ $INTERVALO)
        echo Amostras = $AMOSTRAS, Intervalo = $INTERVALO
        nmon -ft -s $INTERVALO -c $AMOSTRAS
}
case $# in
        2)
                case $1 in
                        dia)
                                if [ $2 -gt 1 ]
                                then
                                        FNMON $BASE_AMOSTRAS  $(expr $2 \* 24)
                                else
                                        FNMON $DIA $(expr $2 \* 24 )
                                fi
                                ;;
                        hora)
                                if [ $2 -gt 24 ]
                                then
                                        FNMON $BASE_AMOSTRAS $2
                                else
                                        FNMON $DIA $2
                                fi
                                ;;
                        *)
                                help
                                ;;
                esac
                ;;
        *)
                help
                ;;
esac

