#!/bin/bash
if [ $# -eq 2 ]
then
	export tamanho=$2
else
	export tamanho=13
fi
[ "$l" == "" ] && l=$tamanho
function HIGH() {
	tr -dc A-Za-z0-9!?@#_ < /dev/urandom | head -c ${l} | xargs
}
function MEDIUM() {
	tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${l} | xargs
}
function LOW() {
	tr -dc A-Za-z0-9 < /dev/urandom | head -c ${l} | xargs
}
function NUMBER() {
	tr -dc 0-9 < /dev/urandom | head -c ${l} | xargs
}
function HEXA() {
	tr -dc A-F0-9 < /dev/urandom | head -c ${l} | xargs
}
function HELP() {
	echo HELP
	echo $(echo $0 | tr '\/' '\n' | tail -n 1) \<numero de caracteres\> \| \[ alto \| medio \| baixo \| numero \| hexa \] \<numero de caracteres\>
	echo $(echo $0 | tr '\/' '\n' | tail -n 1) \[ alto \| medio \| baixo \| numero \| hexa \]
	echo $(echo $0 | tr '\/' '\n' | tail -n 1) \#Opção default utiliza a complexidade alta com $tamanho caracteres
}
case $1 in 
	alto)
		HIGH
		;;
	medio)
		MEDIUM
		;;
	baixo)
		LOW
		;;
	numero)
		NUMBER
		;;
	hexa)
		HEXA
		;;
	help)
		HELP
		;;
	ajuda)
		HELP
		;;
	*)
		re='^[0-9]+$'
		if ! [[ $1 =~ $re ]] 
		then
		   export tamanho=13
		   [ "$l" == "" ] && l=$tamanho
		else
		   export tamanho=$1
		   [ "$l" == "" ] && l=$tamanho
		fi
		HIGH
		;;
esac
