#!/bin/bash -x 
if [ $# -eq 2 ]
then
	export tamanho=$2
else
	export tamanho=13
fi
function HIGH() {
	tr -dc A-Za-z0-9!?@#_ < /dev/urandom | head -c ${tamanho} | xargs
}
function MEDIUM() {
	tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${tamanho} | xargs
}
function LOW() {
	tr -dc A-Za-z0-9 < /dev/urandom | head -c ${tamanho} | xargs
}
function NUMBER() {
	tr -dc 0-9 < /dev/urandom | head -c ${tamanho} | xargs
}
function HEXA() {
	tr -dc A-F0-9 < /dev/urandom | head -c ${tamanho} | xargs
}
function FAKEWWN() {
	tr -dc A-F0-9 < /dev/urandom | head -c 16 | xargs  | sed -e "s/^0x//g" | sed -r "s/../&:/g" | sed -e "s/$://g" | tr "a-z" "A-Z" | sed -e "s/:$//g"
}
function HELP() {
	echo HELP
	echo $(echo $0 | tr '\/' '\n' | tail -n 1) \<numero de caracteres\> \| \[ alto \| medio \| baixo \| numero \| hexa \] \<numero de caracteres\>
	echo $(echo $0 | tr '\/' '\n' | tail -n 1) \[ alto \| medio \| baixo \| numero \| hexa \| fakewwn\]
	echo $(echo $0 | tr '\/' '\n' | tail -n 1) \#Opção default utiliza a complexidade alta com $tamanho caracteres
}
case $1 in 
	alto)
		HIGH
		;;
	medio)
		MEDIUM
		;;
	baixo)
		LOW
		;;
	numero)
		NUMBER
		;;
	hexa)
		HEXA
		;;
	fakewwn)
		FAKEWWN  
		;;
	help)
		HELP
		;;
	ajuda)
		HELP
		;;
	*)
		re='^[0-9]+$'
		if ! [[ $1 =~ $re ]] 
		then
		   export tamanho=13
		else
		   export tamanho=$1
		fi
		HIGH
		;;
esac
